/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { loginInputSchema, userOutputSchema, registerInputSchema } from "../auth/dto/auth.dto.js";
import { getParksInputSchema, parkListOutputSchema, getParkByIdInputSchema, parkDetailOutputSchema, createParkInputSchema } from "../parks/dto/park.dto.js";
import { regionListOutputSchema, getRegionByIdInputSchema, regionDetailOutputSchema, createRegionInputSchema, regionOutputSchema } from "../regions/dto/region.dto.js";
import type { AuthRouter } from "../auth/auth.router.js";

const appRouter = t.router({
  auth: t.router({
    login: publicProcedure
      .input(loginInputSchema)
      .output(userOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    register: publicProcedure
      .input(registerInputSchema)
      .output(userOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    logout: publicProcedure
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<AuthRouter["logout"]>>),
    me: publicProcedure
      .output(userOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  parks: t.router({
    getParks: publicProcedure
      .input(getParksInputSchema)
      .output(parkListOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getParkById: publicProcedure
      .input(getParkByIdInputSchema)
      .output(parkDetailOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createPark: publicProcedure
      .input(createParkInputSchema)
      .output(parkDetailOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  regions: t.router({
    getRegions: publicProcedure
      .output(regionListOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getRegionById: publicProcedure
      .input(getRegionByIdInputSchema)
      .output(regionDetailOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createRegion: publicProcedure
      .input(createRegionInputSchema)
      .output(regionOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
