/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { parkListOutputSchema, parkOutputSchema } from "../parks/dto/park.dto";

const appRouter = t.router({
  parks: t.router({
    getParks: publicProcedure
      .output(parkListOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getParkById: publicProcedure
      .input(z.object({ id: z.uuid() }))
      .output(parkOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
