/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import type { HealthRouter } from "../health/health.router.js";

const appRouter = t.router({
  health: t.router({
    health: publicProcedure
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<HealthRouter["health"]>>)
  }),
  users: t.router({
    getUserById: publicProcedure
      .input(z.object({ userId: z.string() }))
      .output(z.object({
        name: z.string(),
        email: z.string()
      }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  })
});

export type AppRouter = typeof appRouter;
