apiVersion: v1
kind: Service
metadata:
  name: {{ include "park-explorer.apiServiceName" . }}
  labels:
    {{- include "park-explorer.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "park-explorer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.containerPort }}
      targetPort: http
