apiVersion: v1
kind: Service
metadata:
  name: {{ include "park-explorer.postgresServiceName" . }}
  labels:
    {{- include "park-explorer.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  selector:
    {{- include "park-explorer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
