apiVersion: v1
kind: Service
metadata:
  name: {{ include "park-explorer.webServiceName" . }}
  labels:
    {{- include "park-explorer.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "park-explorer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.containerPort }}
      targetPort: http
